[List-Target Action] Allow passing multi-line files
docker/bake-action pull request #247
Opened 2024-09-13 02:58 UTC by shink

Now only support comma-separated values:

```yaml
- uses: docker/bake-action/subaction/list-targets@v5
  with:
    files: arg.json,docker-bake.hcl
```

I just made a quick change, can anyone review it? Thanks!

2024-09-30 09:49 UTC, crazy-max requested changes
Can you also add a new job for testing in https://github.com/docker/bake-action/blob/master/.github/workflows/ci-subaction.yml

Also missing DCO, see https://github.com/docker/bake-action/pull/247/checks?check_run_id=30087916762

2024-09-30 09:49 UTC, crazy-max commented on subaction/list-targets/action.yml
> +            : [];
I think we can just use a regexp for this:

```js
const files = `${{ inputs.files }}` ? `${{ inputs.files }}`.split(/[\r?\n,]+/) : [];
```

2024-09-30 09:54 UTC, shink commented
@crazy-max thanks so much for your review! I'll do this after my holiday.

2024-10-08 08:54 UTC, shink commented
@crazy-max It's ready for review, please take a look and trigger the CI, thanks!

2024-10-08 09:01 UTC, shink commented
ah yes, but the other two jobs are the same. I'm doing some changes to them.

2024-10-08 09:04 UTC, crazy-max commented
> ah yes, but the other two jobs are the same. I'm doing some changes to them.

I think you could just create a `group-multi-files` folder with `docker-bake.hcl` and `docker-bake-2.hcl` files like:

```hcl
# docker-bake.hcl
group "default" {
  targets = ["t1", "t2", "t3"]
}

target "t1" {
  target = "t1"
}

target "t2" {
  target = "t2"
}
```

```hcl
# docker-bake.hcl
target "t3" {
  target = "t3"
}
```

2024-10-08 09:09 UTC, crazy-max approved these changes
LGTM thanks!

2024-10-08 09:09 UTC, merged

2024-10-08 09:11 UTC, shink commented
Thanks for the quick and patient review!